[package]
name = "doc-generator"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12"
thiserror.workspace = true
clap.workspace = true
noirc_frontend.workspace = true
